### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by hollenberry** [githubschool/foolish#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by SCRIC-DAiello** [comment]
I want to be able to solve merge conflicts easily.
💯

**Comment by githubteacher** [comment]
## Two things
1. Write one thing you want to learn before this training ends on Thursday
2. Leave an emoji `:`some word `:` 🌴

**Comment by espittle** [comment]
- How to properly branch/pull/merge
- 😎

**Comment by SCRIC-dmasieh** [comment]
## Two Things
- I would like to get better with Branching
💯 💯 🔥 🔥

**Comment by sculliga** [comment]
1. Learn best practices for GitHub flow and use branches
2. 🥓

**Comment by bsica-SCRIC** [comment]
## Two things
1. Write one thing you want to learn before this training ends on Thursday
Best practices to handle changes in code between teams that might not always communicate on a daily basis.
2. Leave an emoji ':'some word':' 🐈

**Comment by scricbkolb** [comment]
I want to be able to use Github and not break things.
🎸

**Comment by SCRICpbianco** [comment]
I would like learn to use GitHub for website \ configuration versioning 
👍

**Comment by githubteacher** [comment]
@sculliga What do you think about @scricbkolb 's emoji?

**Comment by jpetruzz** [comment]
hello

**Comment by SCRICrtoole** [comment]
Hi
